FROM fedora:31
LABEL maintainer="Factory 2.0"

WORKDIR /src
RUN dnf -y install \
    --setopt=deltarpm=0 \
    --setopt=install_weak_deps=false \
    --setopt=tsflags=nodocs \
    golang \
    git-core \
    mercurial \
    npm \
    python3-celery \
    python3-packaging \
    python3-pip \
    python3-requests \
    python3-requests-kerberos \
    python3-semver \
    python3-setuptools \
    && dnf clean all
COPY . .
RUN pip3 install git+https://github.com/athos-ribeiro/GitPython.git@lazy_get_user#egg=gitpython
RUN pip3 install . --no-deps
EXPOSE 8080
ENV GIT_COMMITTER_NAME=cachito \
    GIT_COMMITTER_EMAIL=cachito@localhost
CMD ["/bin/celery-3", "-A", "cachito.workers.tasks", "worker", "--loglevel=info"]
